### ISSUE TITLE
Error classify_bins module

### ISSUE THREAD

**Issue by palomo11** [bxlab/metaWRAP#4]
Hi,

I have run classify_bins  but it has stopped with the following error:

Log:
```
/home/people/name/.conda/envs/metawrap-env/bin/metawrap-modules/classify_bins.sh -b metaWRAP_bins -o classify_bins -t 28

########################################################################################################################
#####                                   ALIGN CONTIGS TO DATABASE WITH MEGABLAST                                   #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                  setting up ouput folder classify_bins and merging contigs from all bins...                  -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                   aligning classify_bins/all_contigs.fa to                                   -----
-----          /home/projects/env_10000/people/alpal/scripts/NCBI_nt database with MEGABLAST. This is the          -----
-----               longest step - please be patient. You may look at the classification progress in               -----
-----                                       classify_bins/megablast_out.tab                                        -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                  removing unnecessary lines that lead to bad tax IDs (without a proper rank)                 -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                              making mapping file                                             -----
------------------------------------------------------------------------------------------------------------------------


########################################################################################################################
#####                              GET TAXONOMY FROM MEGABLAST OUTPUT WITH TAXATOR-TK                              #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                                   pulling out classifications with taxator                                   -----
------------------------------------------------------------------------------------------------------------------------


************************************************************************************************************************
*****                                       Failed to run taxator. Exiting...                                      *****
************************************************************************************************************************
```
Error:
```An unrecoverable error occurred: std::exception```

Here is some debugging information to locate the problem:
```
/scratch/users/guritsk1@jhu.edu/miniconda2/conda-bld/taxator-kt_1514604714830/work/src/fileparser.hh(52): Throw in function FileParser<FactoryType>::RecordType* FileParser<FactoryType>::next() [with FactoryType = AlignmentRecordFactory<AlignmentRecordTaxonomy>; FileParser<FactoryType>::RecordType = AlignmentRecordTaxonomy]
Dynamic exception type: boost::exception_detail::clone_impl<Exception>
std::exception::what: std::exception
[exception_tag_line*] = 1
[exception_tag_general*] = bad number of fields in alignment line

cat: write error: Broken pipe
```
output folder:
```
458459200 Jan 15 14:11 all_contigs.fa
794859069 Jan 15 16:34 megablast_out.tab
299814468 Jan 15 16:34 mapping.tax
0 Jan 15 16:34 predictions.gff3
```
Looking forward to any help.

Thanks in advance.

**Comment by ursky** [comment]
Interesting... Can you please give run ```head``` on all the output files and give them to me? If the assembly file is does't have linewrap and the first 10 lines are very long, just check yourself that it is in fact a proper fasta file.

**Comment by ursky** [comment]
Thanks! Looks like the cut command somehow merges the 10th and 11th columns in your megablast_out.tab. I was able to replicate it by putting the columns very close together, and fixed it by replacing cut with an awk command. 

This issue has been fixed in `metaWRAP v=0.65`. Please use conda to update, or remake the metaWRAP environment from scratch to be on the safe side.

**Comment by palomo11** [comment]
Hi,

After updating to the new version, it still crashes with same error:

```
An unrecoverable error occurred: std::exception

Here is some debugging information to locate the problem:
/scratch/users/guritsk1@jhu.edu/miniconda2/conda-bld/taxator-kt_1514604714830/work/src/fileparser.hh(52): Throw in function FileParser<FactoryType>::RecordType* FileParser<FactoryType>::next() [with FactoryType = AlignmentRecordFactory<AlignmentRecordTaxonomy>; FileParser<FactoryType>::RecordType = AlignmentRecordTaxonomy]
Dynamic exception type: boost::exception_detail::clone_impl<Exception>
std::exception::what: std::exception
[exception_tag_line*] = 1
[exception_tag_general*] = bad number of fields in alignment line

cat: write error: Broken pipe
```

The assembly file looks like:

head: 60 bases per line

tail: number of bases not delimited.

**Comment by ursky** [comment]
Can you please give me the outputs to `head megablast_out.tab` and `head mapping.tax`?

**Comment by palomo11** [comment]
```
head megablast_out.tab
contig-2165	7756	9959	29190	gi|1002677752|gb|KU516139.1|	27431	25242	1232	0.0	1707	2217
contig-2165	7758	9551	29190	gi|1062756882|gb|CP013136.1|	2164444	2166237	893	0.0	1369	1806
contig-2165	28105	28781	29190	gi|1062756882|gb|CP013136.1|	3265520	3264838	337	1.47e-86	529	695
contig-2165	7761	9532	29190	gi|1148313812|gb|CP019510.1|	4555451	4553682	883	0.0	1349	1780
contig-2165	7764	9534	29190	gi|752314807|gb|CP010536.1|	3026346	3024576	872	0.0	1347	1780
contig-2165	7758	9552	29190	gi|1216455771|gb|CP016434.1|	3716977	3718771	811	0.0	1354	1806
contig-2165	7761	9549	29190	gi|1274761489|gb|CP024608.1|	4206757	4208543	809	0.0	1356	1806
contig-2165	7758	9521	29190	gi|1133509179|emb|LT708274.1|	1	1764	793	0.0	1332	1777
contig-2165	7764	9552	29190	gi|954635978|gb|CP013102.1|	3108721	3106933	784	0.0	1347	1802
contig-2165	7758	9552	29190	gi|1015459287|gb|CP013347.1|	1078385	1080179	761	0.0	1348	1809
```
```
tail megablast_out.tab 
contig-189516	131	193	1116	gi|1001839319|gb|CP014485.1|	1990471	1990533	78.7	3.66e-10	56	63
contig-189516	25	377	1116	gi|947251633|gb|CP009802.1|	633240	633592	99.0	2.81e-16	259	359
contig-189516	131	193	1116	gi|947251633|gb|CP009802.1|	1994337	1994399	78.7	3.66e-10	56	63
contig-189516	149	381	1116	gi|924539656|gb|CP011522.1|	1007058	1007290	99.0	2.81e-16	179	239
contig-189516	127	276	1116	gi|924539656|gb|CP011522.1|	2679160	2679309	84.2	7.87e-12	119	154
contig-189516	125	193	1116	gi|924539656|gb|CP011522.1|	6260946	6260878	84.2	7.87e-12	61	69
contig-189516	32	315	1116	gi|168192641|gb|CP000943.1|	3635479	3635196	99.0	2.81e-16	214	291
contig-189516	149	341	1116	gi|1272225406|gb|CP024029.1|	2746439	2746247	97.1	1.01e-15	151	198
contig-189516	149	341	1116	gi|1272221494|gb|CP024028.1|	2744804	2744612	97.1	1.01e-15	151	198
contig-189833	591	621	1071	gi|374850954|dbj|AP011672.1|	19522	19492	52.8	0.021	30	31
```
```
head mapping.tax
gi|1002677752|gb|KU516139.1|	1781371
gi|1062756882|gb|CP013136.1|	964
gi|1062756882|gb|CP013136.1|	964
gi|1148313812|gb|CP019510.1|	1938606
gi|752314807|gb|CP010536.1|	68895
gi|1216455771|gb|CP016434.1|	1528693
gi|1274761489|gb|CP024608.1|	2045208
gi|1133509179|emb|LT708274.1|	1926495
gi|954635978|gb|CP013102.1|	75105
gi|1015459287|gb|CP013347.1|	75105
```
```
tail mapping.tax
gi|1001839319|gb|CP014485.1|	1888
gi|947251633|gb|CP009802.1|	206662
gi|947251633|gb|CP009802.1|	206662
gi|924539656|gb|CP011522.1|	1649184
gi|924539656|gb|CP011522.1|	1649184
gi|924539656|gb|CP011522.1|	1649184
gi|168192641|gb|CP000943.1|	426117
gi|1272225406|gb|CP024029.1|	536
gi|1272221494|gb|CP024028.1|	536
gi|374850954|dbj|AP011672.1|	120965
```

**Comment by ursky** [comment]
Thanks again. This one was tricky... The problem wasn't with my code (although I found some other issues), but with taxator version control. Turns out their github is actually *behind* their official binary downloads! Never saw that before. 

Anyways, I patched metaWRAP and my Taxator-tk conda package that it uses. Please run `conda uninstall taxator-kt` in your metawrap-env (this should uninstall metaWRAP and Taxator), and then re-install metaWRAP v=0.6.6 `conda install -c ursky metawrap-binning=0.6.6`.

**Comment by palomo11** [comment]
After updating the new version it run fine.

Thanks!

**Comment by ursky** [comment]
Fantastic! Thanks for the feedback.

**Comment by JiaZhong28** [comment]
Hi,I had the same problem when I ran run classify_bins:

`Sender: jhscheduler System <jhadmin@node55>
Subject: Job 6609417: <clean_C3> Done

Job <clean_C3> was submitted from host <node119> by user <2013130172>.
Job was executed on host(s) <20*node55>, in queue <jynodequeue>, as user <2013130172>.
</stor9000/apps/users/NWSUAF/2013130172> was used as the home directory.
</stor9000/apps/users/NWSUAF/2013130172/rumen_microbes/bacteria/metawrap> was used as the working directory.
Started at Fri Jan 11 10:59:06 2019
Results reported at Fri Jan 11 12:47:02 2019

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
bash clean_bin.sh C3
------------------------------------------------------------

Successfully completed.

Resource usage summary:

    CPU time   :  54664.59 sec.
    Max Memory :      5062 MB
    Max Swap   :     15299 MB

    Max Processes  :         6

The output (if any) follows:

metawrap classify_bins -b C3_BIN_REASSEMBLY/reassembled_bins_C75.10 -o C3_BIN_CLASSIFICATION -t 20

########################################################################################################################
#####                                   ALIGN CONTIGS TO DATABASE WITH MEGABLAST                                   #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----              setting up ouput folder C3_BIN_CLASSIFICATION and merging contigs from all bins...              -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                               aligning C3_BIN_CLASSIFICATION/all_contigs.fa to                               -----
-----           /stor9000/apps/users/NWSUAF/2013130172/database/NCBI_nt database with MEGABLAST. This is           -----
-----             the longest step - please be patient. You may look at the classification progress in             -----
-----                                 C3_BIN_CLASSIFICATION/megablast_out.raw.tab                                  -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                  removing unnecessary lines that lead to bad tax IDs (without a proper rank)                 -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                              making mapping file                                             -----
------------------------------------------------------------------------------------------------------------------------


########################################################################################################################
#####                              GET TAXONOMY FROM MEGABLAST OUTPUT WITH TAXATOR-TK                              #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                                   pulling out classifications with taxator                                   -----
------------------------------------------------------------------------------------------------------------------------


************************************************************************************************************************
*****                                       Failed to run taxator. Exiting...                                      *****************************************************************************************************************************



PS:

Read file <C3.err> for stderr output of this job.`

But I use `metaWRAP v=1.0.2`. It seems that this problem appeared again in the new version.

Many thanks!

**Comment by JiaZhong28** [comment]
I have ten samples.Seven of them ran successfully and `bin_taxonomy.tab`  was in my output files.But three of them failed.It seems that metaWRAP itself does not have problems. 


Many thanks!
